apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-api
  template:
    metadata:
      labels:
        app: identity-api
    spec:
      containers:
      - name: identity-api
        image: andresaporito/agrosolutions-agrosolutions-identity-service:latest
        ports:
        - containerPort: 8080
